name: Daily build

on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile
            push: false
            tags: |
                anuruddhal:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
            image-ref: 'anuruddhal:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'   
